<a href="https://colab.research.google.com/github/hasanocal7/DS-Libs/blob/main/NumPy2_Odev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
#1
arr=np.arange(30).reshape(15,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [17]:
#2
arr = np.random.randint(0,10,60).reshape(2,5,-1)
print(f"{arr} \n\n Dimension: {arr.ndim} \n Shape: {arr.shape}")

[[[7 1 3 5 5 6]
  [7 1 7 0 3 9]
  [6 9 9 8 0 7]
  [8 3 1 8 3 9]
  [9 4 0 7 9 4]]

 [[7 9 6 1 6 0]
  [1 8 3 6 0 7]
  [0 1 6 2 1 6]
  [9 7 1 2 7 2]
  [8 9 4 8 4 6]]] 

 Dimension: 3 
 Shape: (2, 5, 6)


In [21]:
#3
arr = np.random.randint(0,10,(5,4))
arr

array([[3, 3, 1, 3],
       [1, 2, 8, 7],
       [0, 4, 9, 6],
       [2, 6, 0, 7],
       [4, 4, 8, 7]])

In [23]:
arr=arr.reshape(-1)
print(f"{arr} \n\n Dimension: {arr.ndim} \n Shape: {arr.shape}")

[3 3 1 3 1 2 8 7 0 4 9 6 2 6 0 7 4 4 8 7] 

 Dimension: 1 
 Shape: (20,)


In [24]:
#4
arr= np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
for i in np.nditer(arr):print(i)

1
2
3
4
5
6


In [35]:
for i in arr:
  for j in i :print(j)

1
2
3
4
5
6


In [41]:
#5
arr1 = np.arange(5,31,5)
arr2 = np.arange(1,7).reshape(3,2)

In [43]:
arr1[1] + arr2[0][1]

12

In [44]:
arr1[1] - arr2[0][1]

8

In [45]:
arr1[1] * arr2[0][1]

20

In [46]:
arr1[1] / arr2[0][1]

5.0

In [47]:
#6
arr = np.random.randint(0,100,10)
print(f"Toplam: {arr.sum()}\nOrtalama: {arr.mean()}\nVaryansı: {arr.var()}\nStandart Sapma: {arr.std()}")

Toplam: 533
Ortalama: 53.3
Varyansı: 841.4100000000001
Standart Sapma: 29.00706810417075


In [48]:
#7
arr1 = np.arange(20)
arr2 = np.arange(500,531)
np.concatenate([arr1,arr2])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [49]:
#8
arr = np.arange(15,51)
att = np.arange(10,101)
ayy = np.concatenate([arr,att])
ayy[25:51] = 888
ayy

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [72]:
#9
arr = np.arange(40).reshape(8,5)
att = np.arange(320,360).reshape(8,5)
con1= np.concatenate([arr,att],axis=0)
con2= np.concatenate([arr,att],axis=1)
print(f"{con1} \n\n Dimension: {con1.ndim} \n Shape: {con1.shape}")
print(f"{con2} \n\n Dimension: {con2.ndim} \n Shape: {con2.shape}")

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]] 

 Dimension: 2 
 Shape: (16, 5)
[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]] 

 Dimension: 2 
 Shape: (8, 10)


In [73]:
#10  # Axis = 2 de concatenate ve stack işlemini kullanmam için iki array in de dimension ı 3 olması gerek yoksa hata alıyor
arr = arr.reshape(4,2,5)
att = att.reshape(4,2,5)
con3 = np.concatenate([arr,att],axis=2)
stk = np.stack([arr,att],axis=2)
print(f"{con3} \n\n Dimension: {con3.ndim} \n Shape: {con3.shape}")
print(f"{stk} \n\n Dimension: {stk.ndim} \n Shape: {stk.shape}")

[[[  0   1   2   3   4 320 321 322 323 324]
  [  5   6   7   8   9 325 326 327 328 329]]

 [[ 10  11  12  13  14 330 331 332 333 334]
  [ 15  16  17  18  19 335 336 337 338 339]]

 [[ 20  21  22  23  24 340 341 342 343 344]
  [ 25  26  27  28  29 345 346 347 348 349]]

 [[ 30  31  32  33  34 350 351 352 353 354]
  [ 35  36  37  38  39 355 356 357 358 359]]] 

 Dimension: 3 
 Shape: (4, 2, 10)
[[[[  0   1   2   3   4]
   [320 321 322 323 324]]

  [[  5   6   7   8   9]
   [325 326 327 328 329]]]


 [[[ 10  11  12  13  14]
   [330 331 332 333 334]]

  [[ 15  16  17  18  19]
   [335 336 337 338 339]]]


 [[[ 20  21  22  23  24]
   [340 341 342 343 344]]

  [[ 25  26  27  28  29]
   [345 346 347 348 349]]]


 [[[ 30  31  32  33  34]
   [350 351 352 353 354]]

  [[ 35  36  37  38  39]
   [355 356 357 358 359]]]] 

 Dimension: 4 
 Shape: (4, 2, 2, 5)


In [74]:
#11
arr = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr == 5)

(array([ 5, 13]),)

In [75]:
#12
np.where(arr %2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [76]:
#13
np.where(arr > 4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [77]:
#14
np.where(arr %5 == 0)

(array([ 1,  2,  5, 13]),)

In [78]:
#15
np.random.randint(85,101)

88

In [79]:
#16
np.random.randint(10,100,(3,3))

array([[72, 10, 73],
       [41, 95, 47],
       [56, 81, 53]])

In [84]:
#17
np.random.choice(np.arange(35,60))

40

In [116]:
#18
arr = np.empty((2,5))

In [120]:
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    arr[i][j] = np.random.choice([3,8,10,53])
arr = arr.astype(int)
arr    

array([[ 3, 10, 10, 53, 10],
       [10, 53,  8, 53,  3]])