<a href="https://colab.research.google.com/github/hasanocal7/DS-Libs/blob/main/NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Bir Array'in Shape'ini Değiştirme

In [ ]:
arr3d = np.array([[ [1,2,3] ,[4,5,6] , [10,25,35] ,[40,50,60]] , [[10,20,30] , [5,10,20] ,[11,22,33] ,[44,55,66] ]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [44, 55, 66]]])

In [ ]:
arr3d.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6, 10, 25, 35, 40, 50, 60],
       [10, 20, 30,  5, 10, 20, 11, 22, 33, 44, 55, 66]])

In [ ]:
arr= np.arange(20)

In [ ]:
arr.shape

(20,)

In [ ]:
arr.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
#Bilinmeyen Boyut
# .reshape metodu kullanılırken hesaplmk istemedeğimiz boyut yeribe -1 yazıp otomtik hesaplattırabiliriz.

In [ ]:
arr3d= np.arange(120).reshape(5,2,-1)

In [ ]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

In [ ]:
# 0-59(59 dahil toplam 60 sayı) arasındaki tam sayılardan oluşan bir array oluşturun. 
# Ardından bu array'in shape'ini değiştirerek istediğiniz shape'lerde 3 boyutlu bir array elde edin.

In [ ]:
arr=np.arange(60).reshape(3,5,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [ ]:
print(arr.ndim,arr.shape)

3 (3, 5, 4)


# Arrayleri Düzleştime (Flatten)

In [ ]:
# DÜzleştirme işlemi çok boyutlu bir array'i 1 boyutlu hale döndürmeye denir.
# Basitçe .reshape(-1) metoduyla yapılır.

In [ ]:
arr2d= np.arange(40).reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
arr2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
arr3d=np.arange(60).reshape(-1,5,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [ ]:
arr3d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
# Soru : 30 elemanlı ve 3 boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve boyutunu, shapeini kontrol edin.

In [ ]:
arr= np.arange(30).reshape(3,5,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [ ]:
arr=arr.reshape(-1)

In [ ]:
print(arr.ndim,arr.shape)

1 (30,)


# Çok Boyutlu Arraylerde Iteration (Yİneleme)



In [ ]:
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in arr1d:print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
arr2d = np.arange(20).reshape(4,5)
for i in arr2d:
  for j in i:
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
arr3d= np.random.randint(1,100,50).reshape(5,5,2)
for i in arr3d:
  for j in i:
    for k in j:
      print(k)

66
7
10
3
55
95
62
14
89
95
55
48
27
89
71
22
65
23
83
91
44
3
14
51
81
34
72
27
72
43
25
96
82
57
76
21
35
59
1
69
23
37
4
72
4
48
37
46
83
75


# Çok Boyutlu Arraylerde nditer() Kullanımı

In [ ]:
# Çok boyutlu arraylerde nditer() fonksiyonu for dan kurtulup tüm elemanları dönmemize yarar

In [ ]:
arr3d

array([[[66,  7],
        [10,  3],
        [55, 95],
        [62, 14],
        [89, 95]],

       [[55, 48],
        [27, 89],
        [71, 22],
        [65, 23],
        [83, 91]],

       [[44,  3],
        [14, 51],
        [81, 34],
        [72, 27],
        [72, 43]],

       [[25, 96],
        [82, 57],
        [76, 21],
        [35, 59],
        [ 1, 69]],

       [[23, 37],
        [ 4, 72],
        [ 4, 48],
        [37, 46],
        [83, 75]]])

In [ ]:
for i in np.nditer(arr3d):
  print(i)

66
7
10
3
55
95
62
14
89
95
55
48
27
89
71
22
65
23
83
91
44
3
14
51
81
34
72
27
72
43
25
96
82
57
76
21
35
59
1
69
23
37
4
72
4
48
37
46
83
75


In [ ]:
# Soru : 0'dan 119'a kadar(119 dahil) toplamda 60 elemanlı bir array oluşturun. Ardından bu array'in shape'ini ayarlayarak 3 boyutlu hale getirin. 
# Devamında da içindeki bütün elemanları tek tek dönün.

In [ ]:
arr = np.arange(120).reshape(2,20,-1)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44],
        [ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89],
        [ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 119]

In [ ]:
for i in np.nditer(arr):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


# Array Elemanları Arasında 4 İşlem

In [ ]:
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,-1])

In [ ]:
arr1 + arr2

array([15, 27, 59, 99])

In [ ]:
arr1.__add__(arr2)

array([15, 27, 59, 99])

In [ ]:
arr1 - arr2

array([  5,  13,  41, 101])

In [ ]:
arr1.__sub__(arr2)

array([  5,  13,  41, 101])

In [ ]:
arr1 * arr2

array([  50,  140,  450, -100])

In [ ]:
arr1 / arr2

array([   2.        ,    2.85714286,    5.55555556, -100.        ])

# Bir Arrayin Toplamına/Ortalamasına/Varyansına/Standart Sapmasına Bakma

In [ ]:
arr = np.random.randint(0,101,10)

In [ ]:
arr.sum()

570

In [ ]:
arr.mean()

57.0

In [ ]:
arr.var()

512.2

In [ ]:
arr.std()

22.631835983852483

In [ ]:
np.sqrt(arr)

array([9.79795897, 6.164414  , 7.74596669, 9.11043358, 9.21954446,
       6.78232998, 6.08276253, 7.61577311, 6.4807407 , 5.        ])

In [ ]:
np.sin(arr)

array([0.98935825, 0.41211849, 0.14112001, 0.98935825, 0.90929743,
       0.14112001, 0.14112001, 0.6569866 , 0.6569866 , 0.6569866 ])

In [ ]:
# Soru : 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [ ]:
arr = np.random.randint(0,100,10)
print(arr.sum(),arr.mean(),arr.var(),arr.std())

424 42.4 583.24 24.150362316122713


# NumPy Arraylerini Birleştirme (Concetanate)

In [ ]:
# NumPy arraylerini birleştirme işlemi np.concatenate fonksiyonu ile yapılır. 
# Fonksiyonun içine liste halinde birleştirerek arrayler verilir
# np.concatenate([arr1,arr2], axis=1)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
np.concatenate([arr1,arr2])

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[4,5,6]])

In [ ]:
np.concatenate([arr1,arr2],axis=1) # axis=1 üzerinde concatenate işlemi yapabilmek için dimension 2d olması gerek

array([[1, 2, 3, 4, 5, 6]])

# Arrayleri Stackleme (Yığınlama)

In [ ]:
# Concatenate işleminin hemen hemen aynısıdır. Tek Farkı yeni bir boyut(eksen) üzerinde yığınamalar yapmasıdır.

In [ ]:
arr1

array([[1, 2, 3]])

In [ ]:
arr2

array([[4, 5, 6]])

In [ ]:
np.stack([arr1,arr2])

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
np.stack([arr1,arr2],axis=1)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
# np.hstack() --> Satır boyunca yığınlama
# np.vstack() --> Sütun boyunca Yığınlama

# NumPy Arraylerinde Arama

In [ ]:
# Aradığımız değerlerin bulunduğu indexleri döndürmek için np.where() fonksiyonunu kullanırız.
# np.where() içerisine argüman olarak condition(şart) alır.

In [ ]:
arr

array([83, 37, 49, 43, 20,  8, 35, 75, 62, 12])

In [ ]:
np.where(arr == 8) # Arrayimizin kaçıncı indexinde istenilen eleman var olduğunu döndürür

(array([5]),)

In [ ]:
np.where(arr%2==0)

(array([4, 5, 8, 9]),)

In [ ]:
#Ekstra
np.random.randn(5) # Normal Dağılım

array([ 0.21686152, -1.47788565,  0.96608266, -0.60215007,  0.32561866])

In [ ]:
np.random.choice(arr) # Arrayin içinden random eleman seçer

75

In [ ]:
# Bitti :). Peace Out <3