<a href="https://colab.research.google.com/github/hasanocal7/DS-Libs/blob/main/NumPy_bitirme_testim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises

Bu zamana kadar gördüğümüz konularla alakalı bilgilerimizi test edelim

<div class="alert alert-danger" style="margin: 10px"><strong>Uyarı!</strong> Output'un üstündeki kod hücrelerini çalıştırmayın !, <br>Aksi takdirde notebooktaki cevap outputlarını kaybedebilirsiniz!</div>

#### 1. NumPy kütüphanesi np kısaltması ile import edin

In [1]:
import numpy as np

#### 2. 10 tane 0 değerinden oluşan bir array oluşturun

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. 10 tane 1 değerinden oluşan bir array oluşturun

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. 10 tane 5 değerinden oluşan bir array oluşturun

In [4]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. 10'dan 50'ye kadar(10 ve 50 dahil) ardışık tam sayılardan oluşan bir array oluşturalım

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. 10 ve 50 arasındaki çift tam sayılardan oluşan bir array oluşturalım. (10 ve 50 dahil)

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. 3x3 shape'inde 0'dan 8'e kadar toplam 9 tam sayıdan oluşan bir array oluşturalım

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. 3x3 boyutlarında birim matris oluşturun

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. NumPy kullanarak 0-1 arasından rastgele bir sayı oluşturun. <br><br>&emsp;NOT: Değerler random seçildiği için sizin sonucunuz aşağıdaki çıktıdan farklı olacaktır

In [11]:
np.random.rand(1)

array([0.82034304])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([0.65248055])

#### 10. NumPy kullanarak standart dağılıma sahip 25 random sayıdan oluşan bir array oluşturalım. <br><br>&emsp;&ensp;NOT: Sizin cevabınız aşağıdaki çıktıdan farklı olacaktır

In [12]:
np.random.randn(25)

array([-0.79025697,  0.73918087, -0.25209655,  0.71063416, -0.00929251,
       -0.90271972,  0.87887949,  1.12509707, -0.49899636, -0.54950108,
       -0.6888716 ,  0.85730135, -3.1067545 , -0.36078431,  0.93682001,
        2.42968652, -1.39621024, -0.17075568,  0.07413303, -0.77046208,
        0.12488302, -0.82558748,  0.60477141, -0.63351095, -0.12428745])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Aşağıdaki çıktıdakine benzer array'i oluşturmaya çalışın

In [22]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. 0-1 arasında lineer artış gösteren ve 20 sayıdan oluşan bir array oluşturun:

In [23]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## NumPy Indexing and Selection

Aşağıdaki matris sıradaki sorular için bizim başlangıç matrisimiz. (Aşağıdaki kod hücresini çalıştırarak devam edin.), devamında sorduğumuz soruları cevaplamaya çalışın:


In [27]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Aşağıda verilen matrisleri oluşturmaya çalışın.<br><br>&emsp;&ensp;Çıktıların üstündeki kod hücresini çalıştırmayın, aksi takdirde çıktıları göremezsiniz

In [123]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code that reproduces the output shown below.

In [124]:
mat[3][-1]

20

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

20

#### 15. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [140]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[ 2],
       [ 7],
       [12]])

#### 16. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [128]:
mat[-1]

array([21, 22, 23, 24, 25])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([21, 22, 23, 24, 25])

#### 17. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

In [142]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. Mat arrayindeki bütün değerlerin toplamını bulun

In [143]:
mat.sum()

325

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

325

#### 19. Mat arrayindeki değerlerin standart sapmasını bulun

In [144]:
mat.std()

7.211102550927978

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

7.211102550927978

#### 20. Mat arrayindeki her sütunun kendi içinde toplamlarını bularak yeni bir array oluşturun

In [153]:
mat_cols_sum=np.empty(5,dtype=int)
for i in range(mat.shape[1]):
  mat_cols_sum[i] = mat[:, i:i+1].sum()
mat_cols_sum

array([55, 60, 65, 70, 75])

In [ ]:
# Bu hücreye kod yazıp çalıştırma !

array([55, 60, 65, 70, 75])

# Tebrikler, NumPy temelleri öğrenilmiş!