<a href="https://colab.research.google.com/github/hasanocal7/DS-Libs/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# NumPy Nedir?


NumPy açık kaynaklı nümerik olarak hızlı matematiksel işlemler yapmamızı sağlayan bir Python kütüphanesidir.

In [ ]:
# NumPy kütüphanesini çağırma;
import numpy as np

# NumPy Array'leri Oluşturma

In [ ]:
# Array oluşturmanın 3 yolu var; 
# 1- np.array([])
# 2- np.arange(), np.linspace(), np.logspace() vb.
# 3- np.random()

0d Array

In [ ]:
array0d=np.array(53)
array0d

array(53)

1D Array

In [ ]:
array1d=np.array([1,2,3,4])
array1d

array([1, 2, 3, 4])

2D Array

In [ ]:
array2d=np.array([[1,2,3],[4,5,6]])
array2d

array([[1, 2, 3],
       [4, 5, 6]])

3D Array

In [ ]:
array3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Örnek bir 2-D Array

In [ ]:
ornek=np.array([[4,8,6],[1,8,9]])
ornek

array([[4, 8, 6],
       [1, 8, 9]])

# Built-in Function ile Hızlıca NumPy Arrayleri Oluşturma

In [ ]:
#np.arange() -> istediğiniz aralıkta ardışık artan array oluşturma
#end-point dahil değil
#range fonk. gibi (start-stop-step) parametlerini alabilir

In [ ]:
arange=np.arange(1,10)
arange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(30,100,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96,
       98])

In [ ]:
#np.linspace() -> arange ten farkı endpoint dahil ve step yerine kaç veri içereceğini gireriz.

In [ ]:
np.linspace(30,50,6)

array([30., 34., 38., 42., 46., 50.])

In [ ]:
np.logspace(1,3,5) # 10^1 10^3 arasında logaritmik artış yapan 5 veriden oluşan array oluşturma

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
# Soru : 10,15,20,25....100 şeklindeki arrayi oluşturunuz.

In [ ]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
# Soru : 0-1000 arasında eşit aralıklarla ilerleyen 26 tane sayı oluşturun.

In [ ]:
np.linspace(0,1000,26)

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [ ]:
# 0'lardan oluşan array

In [ ]:
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# 1'lerden oluşan array

In [ ]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# 5x5 lik birim matris

In [ ]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# 2x6 lık sıfır matrisi

In [ ]:
np.zeros((2,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# np.Random()

In [ ]:
# 3 tane 0-1 aralığında array

In [ ]:
np.random.rand(3)

array([0.45657975, 0.03286186, 0.15867451])

In [ ]:
# 2x5 lik 0-1 aralığında array

In [ ]:
np.random.rand(2,5)

array([[0.27443486, 0.10082576, 0.21986519, 0.083066  , 0.40197457],
       [0.2210652 , 0.76431309, 0.32842713, 0.8039757 , 0.46570557]])

In [ ]:
# 3 tane 0-10 dan oluşan array

In [ ]:
np.random.rand(3) * 10

array([7.58942965, 7.93473168, 8.07331253])

In [ ]:
# 15-50 aralığında 5 verili array

In [ ]:
np.random.randint(15,50,5)

array([38, 44, 43, 18, 19])

In [ ]:
# 0-100 aralığında 3x6 lık random array

In [ ]:
np.random.randint(0,100,(3,6))

array([[20, 49, 98, 55, 96, 37],
       [25, 50,  3, 15, 70, 82],
       [89,  1, 69, 47, 90, 78]])

In [ ]:
# 0-50 aralığında 4x6 lık random array

In [ ]:
np.random.randint(0,50,(4,6))

array([[17, 13, 12,  4, 31,  5],
       [24, 29, 11, 33, 34,  5],
       [14, 39, 46, 11,  3, 27],
       [19, 31,  2, 45, 29, 38]])

# Array'in Boyut Sayısını ve Shape'ini Kontrol Etmek

In [ ]:
# .ndim attribute'i ile arrayin kaç boyutlu olduğunu döndürür

In [ ]:
array1d.ndim

1

In [ ]:
# .shape attribute'i ile arrayin shapei döner

In [ ]:
array2d.shape

(2, 3)

In [ ]:
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
array3d.shape #(adet,satır,sütun)

(1, 3, 3)

# NumPy Arraylerini İndeksleme ve Öğelere erişme

In [ ]:
array1d

array([1, 2, 3, 4])

In [ ]:
array1d[0]

1

In [ ]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array2d[0]

array([1, 2, 3])

In [ ]:
array2d[0][1]

2

In [ ]:
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
array3d[0][0][1]

2

In [ ]:
array3d[0][2][-1]

9

In [ ]:
a=np.arange(53,62) # Örnek soru
a

array([53, 54, 55, 56, 57, 58, 59, 60, 61])

In [ ]:
a[4]

57

# NumPy Dizilerinin Max-Min Elemanlarına Erişme ve İndekslerine Erişme

In [ ]:
arr=np.random.randint(1,100,10)
arr

array([28, 33, 22,  9, 60, 15, 80, 18, 74, 54])

In [ ]:
arr.max()

80

In [ ]:
arr.min()

9

In [ ]:
arr.argmax()

6

In [ ]:
arr.argmin()

3

# NumPy Arraylerinde Slicing(Dilimleme) 

In [ ]:
arr=np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [ ]:
arr[5:11]

array([55, 56, 57, 58, 59, 60])

In [ ]:
arr[-5:]

array([60, 61, 62, 63, 64])

In [ ]:
arr[2:10:2]

array([52, 54, 56, 58])

In [ ]:
arr[5:11]= 999 #Broadcasting
arr

array([ 50,  51,  52,  53,  54, 999, 999, 999, 999, 999, 999,  61,  62,
        63,  64])

In [ ]:
ornek=np.arange(-30,11) #Örnek Soru
ornek

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10])

In [ ]:
ornek1=ornek[5:19] 
ornek1

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

# Bir Array'in Veri Türünü Kontrol Etme

In [ ]:
# .dtype attribute'i ile veri tipi kontrol edilir.

In [ ]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr=np.arange(100,dtype=float)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr=np.array(['a','b','c'])
arr

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
arr.dtype

dtype('<U1')

# Bir Array'in Dtype'ını Değiştirme

In [ ]:
arr=np.array([1.2,3.5,5.8])
arr

array([1.2, 3.5, 5.8])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr=arr.astype('int')
arr

array([1, 3, 5])

In [ ]:
arr = np.array(['5', '7', '19', '1', '22', '99', '4']) #Örnek Soru
arr

array(['5', '7', '19', '1', '22', '99', '4'], dtype='<U2')

In [ ]:
arr=arr.astype(int)

In [ ]:
arr.dtype

dtype('int64')