<a href="https://colab.research.google.com/github/hasanocal7/DS-Libs/blob/main/NumPy1_Odev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#1
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr.ndim

3

In [ ]:
#2
np.arange(34,113,6)

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [ ]:
#3
np.linspace(50,500,91,dtype=int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [ ]:
#4
arr=np.logspace(2,5,8)
arr

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [ ]:
#5
arr=np.arange(0,9)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#6
np.zeros((6,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
#7
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#8
np.eye(8,8,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
#9
np.eye(5,5,dtype=int)*3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [ ]:
#10
np.random.rand(6)

array([0.60518669, 0.70686069, 0.36062075, 0.47525027, 0.63212439,
       0.21537171])

In [ ]:
#11
arr=np.random.randint(50,101,(5,2))
arr

array([[61, 76],
       [93, 94],
       [65, 62],
       [84, 90],
       [64, 52]])

In [ ]:
arr.shape

(5, 2)

In [ ]:
#12
arr=np.random.randint(100,1000,(2,5,5))
arr

array([[[154, 658, 999, 116, 310],
        [160, 157, 340, 133, 903],
        [438, 564, 177, 824, 526],
        [353, 490, 619, 381, 475],
        [326, 283, 967, 555, 958]],

       [[398, 320, 932, 897, 300],
        [208, 642, 693, 985, 958],
        [379, 221, 887, 933, 649],
        [603, 826, 254, 710, 479],
        [672, 431, 800, 164, 802]]])

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(2, 5, 5)

In [ ]:
#13
arr=np.random.randint(0,101,10)
arr

array([69, 56, 92, 18, 10, 89, 24, 42, 15, 50])

In [ ]:
arr.max()

92

In [ ]:
arr.min()

10

In [ ]:
arr.argmax()

2

In [ ]:
arr.argmin()

4

In [ ]:
#14
arr=np.random.randint(300,501,(2,2,5))
arr

array([[[403, 474, 329, 343, 333],
        [457, 305, 454, 458, 421]],

       [[363, 463, 323, 413, 492],
        [466, 456, 331, 475, 356]]])

In [ ]:
arr[1][0][-1]

492

In [ ]:
arr[0][1][1]

305

In [ ]:
#15
arr=np.arange(0,51)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
arr[20:36]=500

In [ ]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])